name: sample_chart_app_server_dart_proj
description: A sample chat application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  json_serializable: ^6.2.0
  build_runner: ^1.12.2
dependencies:
  database: ^0.3.3
  database_adapter_postgre: ^0.2.0
  shelf: ^1.3.0
  shelf_router: ^1.1.2
  shelf_static: ^1.1.0
  json_annotation: ^4.5.0
  get_it: ^7.2.0
  shelf_web_socket: ^1.0.1
  uuid: ^3.0.6
  logger: ^1.1.0
